title: Ting Huang's Homepage
page-top-title: Ting Huang
top-section-bg-text: Computer Science
home-subtitle: Ting Huang&ensp;|&ensp;黄婷
copyright-text: '&copy; Ting Huang 2023-2025. All Rights Reserved.'
